# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check ITR 2 on IncomeTaxPortal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*/30 * * * *"

env:
  WORK_DIR: alerts

jobs:
  cron:
    runs-on: ubuntu-latest
    environment: BUILD_ACTION
    steps:
    - name: Run main script
      run: |
        current=curl -v --silent https://www.incometax.gov.in/iec/foportal/downloads/income-tax-returns 2>&1 | grep -A 28 "Individuals and" | md5sum
        old="d8a24a3cf92c58b0d2fca03d1559edab"
        if [ ${old} == ${current:0:32} ]; then echo "There is no change."; fi
